git clone git@gitcode.com:teemlink/admintools.application
git clone git@gitcode.com:teemlink/afterservice.application
git clone git@gitcode.com:teemlink/contract.application
git clone git@gitcode.com:teemlink/crm.application
git clone git@gitcode.com:teemlink/demo-basic.application
git clone git@gitcode.com:teemlink/demo-bpm.application
git clone git@gitcode.com:teemlink/demo-iscript.application
git clone git@gitcode.com:teemlink/demo-yun.application
git clone git@gitcode.com:teemlink/desk.application
git clone git@gitcode.com:teemlink/finance.application
git clone git@gitcode.com:teemlink/km.application
git clone git@gitcode.com:teemlink/learning.application
git clone git@gitcode.com:teemlink/mes.application
git clone git@gitcode.com:teemlink/oa.application
git clone git@gitcode.com:teemlink/pms.application
git clone git@gitcode.com:teemlink/points.application
git clone git@gitcode.com:teemlink/psi.application
git clone git@gitcode.com:teemlink/psi2.application
git clone git@gitcode.com:teemlink/qms.application
git clone git@gitcode.com:teemlink/srm.application
git clone git@gitcode.com:teemlink/task.application